# Generated by Django 5.0.3 on 2024-06-18 16:42

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumno_convocatoria_solicitudalumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudalumno',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='descripcion',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
