# Generated by Django 5.0.3 on 2024-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_convocatoria_anio_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
