# Generated by Django 5.0.3 on 2024-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alumno_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alumno',
            field=models.BooleanField(default=False),
        ),
    ]
