# Generated by Django 5.0.3 on 2024-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_convocatoria_activa_userprofile_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
