# Generated by Django 5.0.3 on 2024-08-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_convocatoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='sigla',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
