# Generated by Django 5.0.3 on 2024-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_universidad_sigla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudalumno',
            options={'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='solicitudalumno',
            name='estado',
            field=models.CharField(choices=[('p', 'Pendiente'), ('a', 'Aprobado'), ('r', 'rechazado')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
