# Generated by Django 5.0.3 on 2025-04-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_solicitudalumno_options_solicitudalumno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudalumno',
            name='convocatoria',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='solicitudalumno',
            name='alumno',
        ),
        migrations.CreateModel(
            name='ConvocatoriaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('activa', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plazas', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocatoriaExternaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('p', 'Pendiente'), ('a', 'Aprobado'), ('r', 'rechazado')], default='p', max_length=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.convocatoriaexterna')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocatoriaUNQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('activa', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plazas', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('carreras', models.ManyToManyField(to='core.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocatoriaUNQPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('p', 'Pendiente'), ('a', 'Aprobado'), ('r', 'rechazado')], default='p', max_length=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.convocatoriaunq')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocatoriaUNQUniversidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plazas', models.IntegerField()),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.convocatoriaunq')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.universidad')),
            ],
        ),
        migrations.DeleteModel(
            name='Convocatoria',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='SolicitudAlumno',
        ),
    ]
