# Generated by Django 5.0.3 on 2025-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_solicitudalumno_convocatoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='convocatoriaexterna',
            options={'verbose_name_plural': 'Convocatorias Externas'},
        ),
        migrations.AlterModelOptions(
            name='convocatoriaexternasolicitud',
            options={'verbose_name': 'Postulación', 'verbose_name_plural': 'Postulaciones Externas'},
        ),
        migrations.AlterModelOptions(
            name='convocatoriaunq',
            options={'verbose_name': 'Convocatoria UNQ', 'verbose_name_plural': 'Convocatorias UNQ'},
        ),
        migrations.AlterModelOptions(
            name='convocatoriaunqpostulacion',
            options={'verbose_name': 'Postulación', 'verbose_name_plural': 'Postulaciones UNQ'},
        ),
        migrations.AlterModelOptions(
            name='convocatoriaunquniversidad',
            options={'verbose_name': 'Universidad de convocatoria UNQ', 'verbose_name_plural': 'Universidades de convocatoria UNQ'},
        ),
        migrations.AlterField(
            model_name='convocatoriaexternasolicitud',
            name='estado',
            field=models.CharField(choices=[('p', 'Pendiente'), ('a', 'Aprobado'), ('r', 'Rechazado')], default='p', max_length=1),
        ),
    ]
